version: '3.1'

services:
  database:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    env_file:
      - database.env
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql
    networks:
      - my-net


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - database
    links:
      - 'database:db'
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
